// The throttled agent runner used by workflows/adversarial-review.js, and the accounting that
// stops a check which got no verdict from being rendered as a clean one.
//
// WHY IT LIVES HERE: the runner returns the jobs that never produced a result, and for two of its
// three call sites that return value IS the not-run report. On 2026-09-02 the `Coverage-verify`
// call site discarded it (`await runThrottled(...)` with no assignment): one verification check
// died three times, the run recorded `notRun: []`, and a finding judged by 2 of 3 panel lenses was
// reported as if the panel had been whole. Accounting a caller must remember to do is accounting
// that eventually is not done — so it now happens INSIDE the runner, and a caller that wants to
// report leftovers its own way opts out explicitly.
//
// Workflow scripts run sandboxed and cannot import; the two declarations below are mirrored into
// workflows/adversarial-review.js inside a `craft-inline` region and regenerated by
// `node lib/check-workflows.mjs --fix`. They therefore take every dependency as an argument.

// One advisory not-run entry per throttled pass that ended with unfinished jobs — and NONE when the
// pass finished, which is the whole discipline: a marker that fires on healthy runs is one people
// stop reading. Advisory (`incomplete: false`) on purpose: an unjudged check leaves its finding
// reported as Suspected, which is already the honest label, so it does not by itself make the
// verdict INCOMPLETE. An unreviewed *dimension* is the blocking case, and its callers mark it.
export function unjudgedNotRun(tag, unfinished) {
  const count = Array.isArray(unfinished) ? unfinished.length : Number(unfinished) || 0
  if (count <= 0) return []
  const key = String(tag || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'checks'
  return [{
    label: `${key}-checks-unjudged`,
    note: `${count} ${tag} check(s) got no verdict after retries — the findings they were judging stay Suspected`,
    incomplete: false,
  }]
}

// Runs `jobs` in batches of `batch`, retrying whatever produced no result in quieter rounds of
// `retryBatch`, and stops spawning below the budget floor. Returns the jobs that never produced a
// result. Each job: {prompt, label, schema, effort, onResult}.
export function makeThrottledRunner(deps) {
  const { agent, parallel, log, markNotRun, batch: BATCH, retryBatch, maxRetryRounds, budget, budgetFloor } = deps
  return async function runThrottled(jobs, tag, phaseTitle, { reportUnjudged = true } = {}) {
    let pending = jobs
    let done = 0
    let unfinished = null
    for (let round = 0; round <= maxRetryRounds && pending.length && !unfinished; round++) {
      const size = round === 0 ? BATCH : retryBatch
      if (round > 0) log(`${tag} retry round ${round}: ${pending.length} failed calls, batches of ${size}`)
      const failed = []
      for (let i = 0; i < pending.length; i += size) {
        if (budget.total && budget.remaining() < budgetFloor) {
          const skipped = pending.length - i + failed.length
          log(`Budget guard: ~${Math.round(budget.remaining() / 1000)}k tokens left -> stopping ${tag}, ${skipped} calls skipped`)
          unfinished = pending.slice(i).concat(failed)
          break
        }
        const slice = pending.slice(i, i + size)
        const res = await parallel(slice.map(j => () =>
          agent(j.prompt, { label: (round ? `retry${round}:` : '') + j.label, phase: phaseTitle, schema: j.schema, effort: j.effort })))
        res.forEach((v, k) => {
          if (v) { slice[k].onResult(v); done++ } else failed.push(slice[k])
        })
        log(`${tag}: ${done}/${jobs.length} calls done`)
      }
      if (!unfinished) pending = failed
    }
    if (!unfinished) unfinished = pending
    if (reportUnjudged) for (const e of unjudgedNotRun(tag, unfinished)) markNotRun(e.label, e.note, e.incomplete)
    return unfinished
  }
}
