// The throttled agent runner used by workflows/adversarial-review.js, and the accounting that
// stops a check which got no verdict from being rendered as a clean one.
//
// WHY IT LIVES HERE: the runner returns the jobs that never produced a result, and for two of its
// three call sites that return value IS the not-run report. On 2026-09-02 the `Coverage-verify`
// call site discarded it (`await runThrottled(...)` with no assignment): one verification check
// died three times, the run recorded `notRun: []`, and a finding judged by 2 of 3 panel lenses was
// reported as if the panel had been whole. Accounting a caller must remember to do is accounting
// that eventually is not done — so it now happens INSIDE the runner, and a caller that wants to
// report leftovers its own way opts out explicitly.
//
// Workflow scripts run sandboxed and cannot import; the two declarations below are mirrored into
// workflows/adversarial-review.js inside a `craft-inline` region and regenerated by
// `node lib/check-workflows.mjs --fix`. They therefore take every dependency as an argument.

// One not-run entry per throttled pass that ended with unfinished jobs — and NONE when the pass
// finished, which is the whole discipline: a marker that fires on healthy runs is one people stop
// reading.
// It used to claim the unjudged findings "stay Suspected". That was FALSE for an escalated finding:
// its panel members are separate jobs, so one dead lens leaves a 1-1 split that `judge` reads as a
// refutation, and refuted findings are dropped from the report entirely. The premise is now enforced
// at the judge instead of asserted here (a panel that lost a member decides nothing), and this note
// no longer promises an outcome it does not produce.
// Advisory by default, blocking when the pass judged NOTHING — the two are genuinely different: a
// gap in a panel is a weakened judgement, an empty pass is no judgement at all.
/**
 * @param {string} tag
 * @param {unknown[] | number | null | undefined} unfinished
 * @param {{ total?: number }} [opts]
 * @returns {{ label: string, note: string, incomplete: boolean }[]}
 */
export function unjudgedNotRun(tag, unfinished, { total = 0 } = {}) {
  const count = Array.isArray(unfinished) ? unfinished.length : Number(unfinished) || 0
  if (count <= 0) return []
  const key = String(tag || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'checks'
  // A pass that judged NOTHING is not an advisory footnote: no finding in it was verified at all,
  // and a verdict built on that is a verdict about nothing. It downgrades the run like a dead lens.
  const wholePass = total > 0 && count >= total
  return [{
    label: `${key}-checks-unjudged`,
    note: wholePass
      ? `the entire ${tag} pass produced no verdict (${count} check(s)) — nothing it was judging was verified`
      : `${count} ${tag} check(s) got no verdict — the findings they were judging were decided on a partial panel, or not decided at all`,
    incomplete: wholePass,
  }]
}

// Runs `jobs` in batches of `batch`, retrying whatever produced no result in quieter rounds of
// `retryBatch`, and stops spawning below the budget floor. Returns the jobs that never produced a
// result. Each job: {prompt, label, schema, effort, onResult, onMissing?}.
/**
 * @typedef {object} ThrottledJob
 * @property {string} prompt
 * @property {string} label
 * @property {object} [schema]
 * @property {'low' | 'medium' | 'high' | 'xhigh' | 'max'} [effort]
 * @property {(v: unknown) => void} onResult  `v` is the agent's answer (model output), never null
 * @property {() => void} [onMissing]
 */
/**
 * @typedef {object} ThrottledDeps
 * @property {(prompt: string, opts: { label: string, phase: string, schema?: object | undefined, effort?: 'low' | 'medium' | 'high' | 'xhigh' | 'max' | undefined }) => Promise<unknown>} agent
 * @property {(fns: Array<() => Promise<unknown>>) => Promise<unknown[]>} parallel
 * @property {(msg: string) => void} log
 * @property {(label: string, note: string, incomplete: boolean) => void} markNotRun
 * @property {number} batch
 * @property {number} retryBatch
 * @property {number} maxRetryRounds
 * @property {{ total: number | null, remaining: () => number }} budget  `total` is null when no token target was set
 * @property {number} budgetFloor
 */
/**
 * @param {ThrottledDeps} deps
 * @returns {(jobs: ThrottledJob[], tag: string, phaseTitle: string, opts?: { reportUnjudged?: boolean }) => Promise<ThrottledJob[]>}
 */
export function makeThrottledRunner(deps) {
  const { agent, parallel, log, markNotRun, batch: BATCH, retryBatch, maxRetryRounds, budget, budgetFloor } = deps
  // One round over `pending` in batches of `size`: the jobs that produced no result, and — when the
  // budget guard stopped the round — every job left unfinished (null when it ran to the end).
  /**
   * @param {ThrottledJob[]} pending
   * @param {number} size
   * @param {number} round
   * @param {string} tag
   * @param {string} phaseTitle
   * @param {{ done: number, jobs: ThrottledJob[] }} progress  `done` counts across rounds
   * @returns {Promise<{ failed: ThrottledJob[], unfinished: ThrottledJob[] | null }>}
   */
  const runRound = async (pending, size, round, tag, phaseTitle, progress) => {
    /** @type {ThrottledJob[]} */
    const failed = []
    for (let i = 0; i < pending.length; i += size) {
      if (budget.total && budget.remaining() < budgetFloor) {
        const skipped = pending.length - i + failed.length
        log(`Budget guard: ~${Math.round(budget.remaining() / 1000)}k tokens left -> stopping ${tag}, ${skipped} calls skipped`)
        return { failed, unfinished: pending.slice(i).concat(failed) }
      }
      const slice = pending.slice(i, i + size)
      const res = await parallel(slice.map(j => () =>
        agent(j.prompt, { label: (round ? `retry${round}:` : '') + j.label, phase: phaseTitle, schema: j.schema, effort: j.effort })))
      res.forEach((v, k) => {
        if (v) { /** @type {ThrottledJob} */ (slice[k]).onResult(v); progress.done++ } else failed.push(/** @type {ThrottledJob} */ (slice[k]))
      })
      log(`${tag}: ${progress.done}/${progress.jobs.length} calls done`)
    }
    return { failed, unfinished: null }
  }
  /**
   * @param {ThrottledJob[]} unfinished
   * @param {string} tag
   * @param {number} total
   * @param {boolean} reportUnjudged
   */
  const settle = (unfinished, tag, total, reportUnjudged) => {
    // A job that never produced a verdict must leave a TRACE where the verdict would have gone, not
    // only a line in the run record. Its absence is what the judge has to see: a panel silently one
    // vote short reads as a whole panel, and a 1-1 split then counts as a refutation.
    for (const j of unfinished) if (typeof j.onMissing === 'function') j.onMissing()
    // `total` lets the entry tell a gap apart from a pass that judged nothing — including the pass
    // stopped by the budget guard before it spawned its first agent, which returned an empty
    // leftover list and therefore reported as clean.
    if (reportUnjudged) for (const e of unjudgedNotRun(tag, unfinished, { total })) markNotRun(e.label, e.note, e.incomplete)
  }
  return async function runThrottled(jobs, tag, phaseTitle, { reportUnjudged = true } = {}) {
    let pending = jobs
    const progress = { done: 0, jobs }
    /** @type {ThrottledJob[] | null} */
    let unfinished = null
    for (let round = 0; round <= maxRetryRounds && pending.length && !unfinished; round++) {
      const size = round === 0 ? BATCH : retryBatch
      if (round > 0) log(`${tag} retry round ${round}: ${pending.length} failed calls, batches of ${size}`)
      const ran = await runRound(pending, size, round, tag, phaseTitle, progress)
      unfinished = ran.unfinished
      if (!unfinished) pending = ran.failed
    }
    if (!unfinished) unfinished = pending
    settle(unfinished, tag, jobs.length, reportUnjudged)
    return unfinished
  }
}
